# Generated by Django 5.1.3 on 2024-11-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', 'Flower'), ('tree', 'Tree'), ('herb', 'Herb'), ('succulent', 'Succulent')], max_length=2048),
        ),
    ]
